
# Copyright (C) 2018-2019 Andrew Hamilton. All rights reserved.
# Licensed under the Artistic License 2.0.

tools_for_extensions = [
   [["py"], ["python_syntax", "python_unittests", "pydoc", "mypy",
             "python_coverage", "pycodestyle", "pydocstyle", "pyflakes",
	     "pylint", "python_gut", "python_modulefinder", "dis",
	     "python_mccabe", "bandit"]],
#    [["pyc"], ["pydisasm"]],
   [["pl", "pm", "t"], ["perl_syntax", "perldoc"]],
   [["p6", "pm6"], ["perl6_syntax"]],
   [["pod", "pod6"], ["perldoc"]],
   [["c", "h"], ["c_syntax_gcc", "cppcheck"]],
   [["cc", "cpp", "hpp"], ["cpp_syntax_gcc", "cppcheck"]],
   [["rb"], ["ruby_syntax"]],
   [["lua"], ["lua_syntax", "lua_check"]],
   [["js"], ["js_syntax"]],
   [["php"], ["php7_syntax"]],
   [["go"], ["go_vet", "golint", "godoc"]],
   [["bash", "sh", "dash", "ksh"], ["shellcheck"]],
   [["wasm"], ["wasm_validate", "wasm_objdump"]],
   [["pdf"], ["pdf2txt"]],
   [["html", "htm"], ["html_syntax", "html2text", "elinks"]],
   [["yaml", "yml"], ["yamllint"]],
   [["md", "epub", "docx", "odt", "rst"], ["pandoc"]],
   [["zip", "jar", "apk", "egg", "whl"], ["zipinfo"]],
   [["tar.gz", "tgz"],["tar_gz"]],
   [["tar.bz2"], ["tar_bz2"]],
   [["rar"], ["unrar"]],
   [["7z"], ["7z"]],
   [["xz"], ["unxz"]],
   [["a"], ["ar", "nm"]],
   [["o"], ["objdump_headers", "objdump_disassemble", "readelf"]],
   [["so"], ["nm"]],   
   [["deb"], ["dpkg_contents", "dpkg_info"]],
   [["rpm"], ["rpm"]],
   [["png", "jpg", "gif", "bmp", "tif", "tiff", "tga"], ["mediainfo", "pil"]],
   [["svg", "svgz"], ["svglib"]],
   [["mkv", "mka", "mks", "ogg", "ogm", "avi", "wav", "mpeg", "mpg", "vob",
     "mp4", "mpgv", "mpv", "m1v", "m2v", "mp2", "mp3", "asf", "wma", "wmv",
     "qt", "mov", "rm", "rmvb", "ra", "ifo", "ac3", "dts", "aac", "flac",
     "aiff", "aifc", "au", "iff", "flv", "srt", "ssa", "ass", "sami"],
     ["mediainfo"]],
   [["iso"], ["isoinfo"]],
   ]


[python_syntax]
  dependencies = []
  url = "https://en.wikipedia.org/wiki/Python_syntax_and_semantics"
  command = "python3.7 -m py_compile"

[pycodestyle]
  dependencies = ["pip/pycodestyle"]
  url = "http://pycodestyle.pycqa.org/en/latest/"
  command = "python3.7 -m pycodestyle"

[pydocstyle]
  dependencies = ["pip/pydocstyle"]
  url = "http://www.pydocstyle.org/en/2.1.1/usage.html"
  command = "python3.7 -m pydocstyle --ignore=D1"

[pyflakes]
  dependencies = ["pip/pyflakes"]
  url = "https://pypi.org/project/pyflakes/"
  command = "python3.7 -m pyflakes"

[pylint]
  dependencies = ["pip/pylint"]
  url = "https://www.pylint.org/"
  command = "python3.7 -m pylint -f colorized --errors-only"
  has_color = true

[python_modulefinder]
  dependencies = []
  url = "https://docs.python.org/3/library/modulefinder.html"
  command = "python3.7 -m modulefinder"
  success_status = "normal"

[bandit]
  dependencies = ["pip/bandit"]
  url = "https://pypi.org/project/bandit/"
  command = "python3.7 -m bandit.cli.main -f screen"
  has_color = true
  timeout = 60

[perl_syntax]
  dependencies = ["perl"]
  url = "https://en.wikipedia.org/wiki/Perl"
  command = "perl -c"

[perl6_syntax]
  dependencies = ["rakudo"]
  url = "https://rakudo.org/"
  command = "perl6 -c"
  has_color = true

[git_blame]
  dependencies = ["git"]
  url = "https://git-scm.com/docs/git-blame"
  command = "git blame --show-stats --date=short --color-lines --color-by-age"
  success_status = "normal"
  error_status = "not_applicable"
  has_color = true

[git_log]
  dependencies = ["git"]
  url = "https://git-scm.com/docs/git-log"
  command = "git log --find-renames --follow --stat --color"
  success_status = "normal"
  error_status = "not_applicable"
  has_color = true

[dis]
  dependencies = []
  url = "https://docs.python.org/3/library/dis.html"
  command = "python3.7 -m dis"
  success_status = "normal"

[objdump_headers]
  dependencies = ["binutils"]
  url = "https://en.wikipedia.org/wiki/Objdump"
  command = "objdump --all-headers"
  success_status = "normal"

[objdump_disassemble]
  dependencies = ["binutils"]
  url = "https://en.wikipedia.org/wiki/Objdump"
  command = "objdump --disassemble --reloc --dynamic-reloc"
  success_status = "normal"

[readelf]
  dependencies = ["binutils"]
  url = "https://en.wikipedia.org/wiki/Objdump"
  command = "readelf --all"
  success_status = "normal"

[zipinfo]
  dependencies = ["unzip"]
  command = "zipinfo"
  success_status = "normal"

[tar_gz]
  dependencies = ["tar"]
  url = "http://www.gnu.org/software/tar/manual/tar.html"
  command = "tar ztvf"
  success_status = "normal"

[tar_bz2]
  dependencies = ["tar"]
  url = "http://www.gnu.org/software/tar/manual/tar.html"
  command = "tar jtvf"
  success_status = "normal"

[unrar]
  dependencies = ["unrar"]
  command = "unrar l"
  success_status = "normal"

[7z]
  dependencies = ["p7zip"]
  command = "7z l"
  success_status = "normal"

[unxz]
  dependencies = ["xz-utils"]
  command = "unxz --list"
  success_status = "normal"

[dpkg_contents]
  dependencies = ["dpkg"]
  command = "dpkg --contents"
  success_status = "normal"

[dpkg_info]
  dependencies = ["dpkg"]
  command = "dpkg --info"
  success_status = "normal"

[rpm]
  dependencies = ["rpm"]
  command = "rpm --query --list"
  success_status = "normal"

[ar]
  dependencies = ["binutils"]
  url = "https://en.wikipedia.org/wiki/Ar_(Unix)"
  command = "ar t"
  success_status = "normal"

[nm]
  dependencies = ["binutils"]
  url = "https://linux.die.net/man/1/nm"
  command = "nm --demangle"
  success_status = "normal"

[pdf2txt]
  dependencies = ["pip/pdfminer.six", "pip/chardet"]
  url = "https://github.com/pdfminer/pdfminer.six"
  command = "pdf2txt.py"
  success_status = "normal"

[html2text]
  dependencies = ["html2text"]
  command = "html2text"
  success_status = "normal"

[elinks]
  dependencies = ["elinks"]
  command = "elinks -dump-color-mode 1 -dump"
  success_status = "normal"
  has_color = true

[c_syntax_gcc]
  dependencies = ["gcc", "g++"]
  url = "https://gcc.gnu.org/"
  command = "gcc -fsyntax-only -fdiagnostics-color=always"
  has_color = true

[cpp_syntax_gcc]
  dependencies = ["gcc", "g++"]
  url = "https://gcc.gnu.org/"
  command = "gcc -fsyntax-only -fdiagnostics-color=always"
  has_color = true

[php7_syntax]
  dependencies = ["php7.2-cli"]
  url = "https://en.wikipedia.org/wiki/PHP"
  command = "php --syntax-check"

[identify]
  dependencies = ["imagemagick"]
  url = "http://www.imagemagick.org/script/identify.php"
  command = "identify -verbose"
  success_status = "normal"

[shellcheck]
  dependencies = ["shellcheck"]
  command = "shellcheck --color=always"
  has_color = true

[cppcheck]
  dependencies = ["cppcheck"]
  command = "cppcheck"

[ruby_syntax]
  dependencies = ["ruby2.5"]
  command = "ruby -c"

[lua_syntax]
  dependencies = ["lua5.3"]
  command = "luac -p"

[js_syntax]
  dependencies = ["nodejs"]
  command = "node --check"

[lua_check]
  dependencies = ["luarocks/luacheck"]
  url = "https://github.com/mpeterv/luacheck"
  command = "luacheck"
  has_color = true

[go_vet]
  dependencies = ["go/github.com/golang/go/src/cmd/vet"]
  url = "https://github.com/golang/go"
  command = "vet"

[golint]
  dependencies = ["go/github.com/golang/lint/golint"]
  url = "https://github.com/golang/lint"
  command = "golint -set_exit_status"

[wasm_validate]
  dependencies = ["git/github.com/WebAssembly/wabt"]
  url = "https://github.com/WebAssembly/wabt"
  command = "wasm-validate"

[wasm_objdump]
  dependencies = ["git/github.com/WebAssembly/wabt"]
  url = "https://github.com/WebAssembly/wabt"
  command = "wasm-objdump --disassemble"
  success_status = "normal"

[yamllint]
  dependencies = ["pip/yamllint"]
  url = "https://github.com/adrienverge/yamllint"
  command = "python3.7 -m yamllint -f colored"
  has_color = true

[mediainfo]
  dependencies = ["mediainfo"]
  command = "mediainfo"
  success_status = "normal"

[isoinfo]
  dependencies = ["genisoimage"]
  url = "https://manpages.debian.org/jessie/genisoimage/isoinfo.1.en.html"
  command = "isoinfo -l -i"
  success_status = "normal"
