#!/bin/bash

# Copyright (C) 2018 Andrew Hamilton. All rights reserved.
# Licensed under the Artistic License 2.0.


set -e


DIST_ID=$(cat /etc/os-release | grep "^ID=" | cut -d "=" -f 2)
if [ $DIST_ID != "ubuntu" ]; then
    echo "Vigil can only be installed on Ubuntu."
    exit 1
fi
echo "Installing the dependencies of the vigil script..."
sudo apt --yes install python3.7 util-linux
python3.7 -m pip install pyinotify pygments docopt pillow toml
echo
echo "Installing all the tools vigil may need..."
./install-tools
