tools_for_extensions = [
   [["py"], ["python_syntax", "python_unittests", "pydoc", "mypy",
             "python_coverage", "pycodestyle", "pyflakes", "pylint",
             "python_gut", "python_modulefinder", "dis", "python_mccabe",
             "bandit"]],
#    [["pyc"], ["pydisasm"]],
   [["pl", "pm", "t"], ["perl_syntax", "perldoc", "perltidy"]],
#    [["p6", "pm6"], ["perl6_syntax", "perldoc"]],
   [["pod", "pod6"], ["perldoc"]], [["java"], ["uncrustify"]],
   [["c", "h"], ["c_syntax_gcc", "splint", "uncrustify", "cppcheck"]],
   [["o"], ["objdump_headers", "objdump_disassemble", "readelf"]],
   [["cc", "cpp", "hpp"], ["cpp_syntax_gcc", "bcpp", "uncrustify",
                           "cppcheck"]],
   [["pdf"], ["pdf2txt"]],
   [["html"], ["html_syntax", "tidy", "html2text"]],
   [["php"], ["php7_syntax"]],
   [["zip"], ["unzip"]],
   [["tar.gz", "tgz"],["tar_gz"]],
   [["tar.bz2"], ["tar_bz2"]],
   [["a", "so"], ["nm"]],
   [["png", "jpg", "gif", "bmp", "ppm", "tiff", "tga"], ["pil", "pil_half"]],
   [["bash", "sh", "dash", "ksh"], ["shellcheck"]],
   [["go"], ["gofmt", "go_vet", "golint", "godoc"]],
   [["yaml"], ["yamllint"]]]


# Tool template:
# []
#   dependencies = [""]
#   url = ""
#   command = ""
#   success_status = ""
#   error_status = ""

[objdump_headers]
  dependencies = ["binutils"]
  url = "https://en.wikipedia.org/wiki/Objdump"
  command = "objdump --all-headers"
  success_status = "normal"

[objdump_disassemble]
  dependencies = ["binutils"]
  url = "https://en.wikipedia.org/wiki/Objdump"
  command = "objdump --disassemble --reloc --dynamic-reloc"
  success_status = "normal"

[readelf]
  dependencies = ["binutils"]
  url = "https://en.wikipedia.org/wiki/Objdump"
  command = "readelf --all"
  success_status = "normal"

[unzip]
  dependencies = ["unzip"]
  url = "unzip"
  command = "unzip -l"
  success_status = "normal"

[tar_gz]
  dependencies = ["tar"]
  url = "http://www.gnu.org/software/tar/manual/tar.html"
  command = "tar ztvf"
  success_status = "normal"

[tar_bz2]
  dependencies = ["tar"]
  url = "http://www.gnu.org/software/tar/manual/tar.html"
  command = "tar jtvf"
  success_status = "normal"

[nm]
  dependencies = ["binutils"]
  url = "https://linux.die.net/man/1/nm"
  command = "nm --demangle"
  success_status = "normal"

[pdf2txt]
  dependencies = ["python-pdfminer"]
  url = "python-pdfminer"
  command = "pdf2txt"
  success_status = "normal"

[html2text]
  dependencies = ["html2text"]
  url = "html2text"
  command = "html2text"
  success_status = "normal"

[c_syntax_gcc]
  dependencies = ["gcc", "g++-6"]
  url = "https://gcc.gnu.org/"
  command = "gcc -fsyntax-only"

[cpp_syntax_gcc]
  dependencies = ["gcc", "g++-6"]
  url = "https://gcc.gnu.org/"
  command = "gcc -fsyntax-only"

[php7_syntax]
  dependencies = ["php7.2-cli"]
  url = "https://en.wikipedia.org/wiki/PHP"
  command = "php7.2 --syntax-check"

[shellcheck]
  dependencies = ["shellcheck"]
  url = "shellcheck"
  command = "shellcheck"

[cppcheck]
  dependencies = ["cppcheck"]
  url = "cppcheck"
  command = "cppcheck"

[gofmt]
  dependencies = ["golang-go"]
  url = "golang-go"
  command = "gofmt"
  success_status = "normal"

[go_vet]
  dependencies = ["golang-go"]
  url = "golang-go"
  command = "go vet"
  error_status = "normal"

[golint]
  dependencies = ["golint"]
  url = "golint"
  command = "golint -set_exit_status"
  error_status = "normal"

[yamllint]
  dependencies = ["yamllint"]
  url = "yamllint"
  command = "yamllint"
