
# Copyright (C) 2018 Andrew Hamilton. All rights reserved.
# Licensed under the Artistic License 2.0.

tools_for_extensions = [
   [["py"], ["python_syntax", "python_unittests", "pydoc", "mypy",
             "python_coverage", "pycodestyle", "pydocstyle", "pyflakes",
	     "pylint", "python_gut", "python_modulefinder", "dis",
	     "python_mccabe", "bandit"]],
#    [["pyc"], ["pydisasm"]],
   [["pl", "pm", "t"], ["perl_syntax", "perldoc", "perltidy"]],
#    [["p6", "pm6"], ["perl6_syntax", "perldoc"]],
   [["pod", "pod6"], ["perldoc"]], [["java"], ["uncrustify"]],
   [["c", "h"], ["c_syntax_gcc", "splint", "uncrustify", "cppcheck"]],
   [["o"], ["objdump_headers", "objdump_disassemble", "readelf"]],
   [["cc", "cpp", "hpp"], ["cpp_syntax_gcc", "bcpp", "uncrustify",
                           "cppcheck"]],
   [["pdf"], ["pdf2txt"]],
   [["html", "htm"], ["html_syntax", "tidy", "html2text", "pandoc"]],
   [["php"], ["php7_syntax"]],
   [["zip", "jar", "apk"], ["zipinfo"]],
   [["tar.gz", "tgz"],["tar_gz"]],
   [["tar.bz2"], ["tar_bz2"]],
   [["a", "so"], ["nm"]],
   [["png", "jpg", "gif", "bmp", "ppm", "tiff", "tga"], ["identify", "pil",
                                                         "pil_half"]],
   [["bash", "sh", "dash", "ksh"], ["shellcheck"]],
   [["go"], ["gofmt", "go_vet", "golint", "godoc"]],
   [["yaml", "yml"], ["yamllint"]],
   [["md", "epub", "docx", "odt", "rst"], ["pandoc"]],
   [["mkv", "mka", "mks", "ogg", "ogm", "avi", "wav", "mpeg", "mpg", "vob",
     "mp4", "mpgv", "mpv", "m1v", "m2v", "mp2", "mp3", "asf", "wma", "wmv",
     "qt", "mov", "rm", "rmvb", "ra", "ifo", "ac3", "dts", "aac", "flac",
     "aiff", "aifc", "au", "iff", "flv"], ["mediainfo"]],
   ]

[git_blame]
  dependencies = ["git"]
  url = "https://git-scm.com/docs/git-blame"
  command = "git blame --show-stats --date=short"
  success_status = "normal"
  error_status = "not_applicable"

[git_log]
  dependencies = ["git"]
  url = "https://git-scm.com/docs/git-log"
  command = "git log --find-renames --follow --stat"
  success_status = "normal"
  error_status = "not_applicable"

[objdump_headers]
  dependencies = ["binutils"]
  url = "https://en.wikipedia.org/wiki/Objdump"
  command = "objdump --all-headers"
  success_status = "normal"

[objdump_disassemble]
  dependencies = ["binutils"]
  url = "https://en.wikipedia.org/wiki/Objdump"
  command = "objdump --disassemble --reloc --dynamic-reloc"
  success_status = "normal"

[readelf]
  dependencies = ["binutils"]
  url = "https://en.wikipedia.org/wiki/Objdump"
  command = "readelf --all"
  success_status = "normal"

[zipinfo]
  dependencies = ["unzip"]
  url = "unzip"
  command = "zipinfo"
  success_status = "normal"

[tar_gz]
  dependencies = ["tar"]
  url = "http://www.gnu.org/software/tar/manual/tar.html"
  command = "tar ztvf"
  success_status = "normal"

[tar_bz2]
  dependencies = ["tar"]
  url = "http://www.gnu.org/software/tar/manual/tar.html"
  command = "tar jtvf"
  success_status = "normal"

[nm]
  dependencies = ["binutils"]
  url = "https://linux.die.net/man/1/nm"
  command = "nm --demangle"
  success_status = "normal"

[pdf2txt]
  dependencies = ["python-pdfminer"]
  url = "python-pdfminer"
  command = "pdf2txt"
  success_status = "normal"

[html2text]
  dependencies = ["html2text"]
  url = "html2text"
  command = "html2text"
  success_status = "normal"

[pandoc]
  dependencies = ["pandoc"]
  url = "pandoc"
  command = "pandoc -t plain"
  success_status = "normal"

[c_syntax_gcc]
  dependencies = ["gcc", "g++-6"]
  url = "https://gcc.gnu.org/"
  command = "gcc -fsyntax-only"

[cpp_syntax_gcc]
  dependencies = ["gcc", "g++-6"]
  url = "https://gcc.gnu.org/"
  command = "gcc -fsyntax-only"

[php7_syntax]
  dependencies = ["php7.2-cli"]
  url = "https://en.wikipedia.org/wiki/PHP"
  command = "php7.2 --syntax-check"

[identify]
  dependencies = ["imagemagick"]
  url = "http://www.imagemagick.org/script/identify.php"
  command = "identify -verbose"
  success_status = "normal"

[shellcheck]
  dependencies = ["shellcheck"]
  url = "shellcheck"
  command = "shellcheck"

[cppcheck]
  dependencies = ["cppcheck"]
  url = "cppcheck"
  command = "cppcheck"

[gofmt]
  dependencies = ["golang-go"]
  url = "golang-go"
  command = "gofmt"
  success_status = "normal"

[go_vet]
  dependencies = ["golang-go"]
  url = "golang-go"
  command = "go vet"
  error_status = "normal"

[golint]
  dependencies = ["golint"]
  url = "golint"
  command = "golint -set_exit_status"
  error_status = "normal"

[yamllint]
  dependencies = ["yamllint"]
  url = "yamllint"
  command = "yamllint"

[mediainfo]
  dependencies = ["mediainfo"]
  url = "mediainfo"
  command = "mediainfo"
  success_status = "normal"
