#!/bin/sh


# This is a modified version of the AppRun made by AppImage's meta/Recipe.


set -e


HERE="$(dirname "$(readlink -f "${0}")")"
export APPDIR="${HERE}"
export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/local/bin/:"${PATH}"
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD="${HERE}/libunionpreload.so"
export LD_LIBRARY_PATH="${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib32/:"${HERE}"/usr/lib64/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${HERE}"/lib32/:"${HERE}"/lib64/:"${LD_LIBRARY_PATH}"
export PYTHONPATH=/usr/local/lib/python3.5/dist-packages:"${PYTHONPATH}"
if [ -z $APPIMAGE_ENTER ]; then
    EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
    exec ${EXEC} $@
else
    if [ -z "$@" ]; then
	exec /bin/bash
    else
	$@
    fi
fi
